// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(DeliveryAppContext))]
    [Migration("20230901222238_fourth-migration")]
    partial class fourthmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.Models.UbicacionVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaUltimaUbicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UbicacionVehiculoCoordenadasId")
                        .HasColumnType("bigint");

                    b.Property<long>("VehiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionVehiculoCoordenadasId");

                    b.ToTable("UbicacionesVehiculo");
                });

            modelBuilder.Entity("DB.Models.UbicacionVehiculoCoordenadas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("latitud")
                        .HasColumnType("real");

                    b.Property<float>("longitud")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("UbicacionVehiculoCoordenadas");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<float>("latitud")
                        .HasColumnType("real");

                    b.Property<float>("longitud")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.HistorialUbicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UbicacionVehiculoCoordenadasId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionVehiculoCoordenadasId");

                    b.ToTable("HistorialUbicaciones");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Aceptado")
                        .HasColumnType("boolean");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Commentarios")
                        .HasColumnType("text");

                    b.Property<bool>("Entregado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("HoraCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.Property<long?>("VehiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Matricula")
                        .HasColumnType("text");

                    b.Property<string>("NombreConductor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("DB.Models.UbicacionVehiculo", b =>
                {
                    b.HasOne("DB.Models.UbicacionVehiculoCoordenadas", "UbicacionVehiculoCoordenadas")
                        .WithMany()
                        .HasForeignKey("UbicacionVehiculoCoordenadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UbicacionVehiculoCoordenadas");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.HistorialUbicacion", b =>
                {
                    b.HasOne("DB.Models.UbicacionVehiculoCoordenadas", "UbicacionVehiculoCoordenadas")
                        .WithMany()
                        .HasForeignKey("UbicacionVehiculoCoordenadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UbicacionVehiculoCoordenadas");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.Pedido", b =>
                {
                    b.HasOne("Delivery_App_Code_Challenge.DB.Models.Vehiculo", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("VehiculoId");
                });

            modelBuilder.Entity("Delivery_App_Code_Challenge.DB.Models.Vehiculo", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
