version: '3.4'

services:
  delivery-app-code-challenge:
    image: ${DOCKER_REGISTRY-}deliveryappcodechallenge
    build:
      context: .
      dockerfile: Delivery-App-Code-Challenge/Dockerfile
    environment:
     ConnectionStrings_DefaultConnection: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
     - db
  db:
   container_name: db
   image: postgres:13
   ports:
   - "5432:5432"
   environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
   volumes:
   - pgdata:/var/lib/postresql/data
 
volumes:
 pgdata: {}

